### ISSUE TITLE
jq does not work with Github Actions

### ISSUE THREAD

**Issue by grtn316** [stedolan/jq#2287]
I am trying to parse json objects during deploying using Github Actions. I am getting an error that I cannot seem to get around no matter the configuration.

When running a command like:
`terraform version -json | jq .`

I get the following error:
```
parse error: Invalid numeric literal at line 1, column 9
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Socket.<anonymous> (/home/runner/work/_temp/9e3adb1b-f01b-4275-be6d-1d579d82a4a7/terraform:750:54)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

The output should look like this:
```
{
  "terraform_version": "0.14.8",
  "terraform_revision": "",
  "provider_selections": {
    "registry.terraform.io/hashicorp/azuread": "1.3.0",
    "registry.terraform.io/hashicorp/azurerm": "2.47.0",
    "registry.terraform.io/hashicorp/cloudinit": "2.1.0",
    "registry.terraform.io/hashicorp/external": "2.0.0",
    "registry.terraform.io/hashicorp/kubernetes": "2.0.2",
    "registry.terraform.io/hashicorp/local": "2.0.0",
    "registry.terraform.io/hashicorp/null": "3.0.0",
    "registry.terraform.io/hashicorp/template": "2.2.0",
    "registry.terraform.io/hashicorp/tls": "3.0.0"
  },
  "terraform_outdated": false
}
```

Action YML
```
name: Deploy To Azure
on:
  workflow_dispatch:
    inputs:
      location:
          description: 'Deployment region'
          required: true
          default: 'eastus'
jobs:
  deploy-to-azure:
    name: 'Deploy to Azure'
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Set Terraform Version'
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.14.8

      - name: 'Terraform Init'
        id: init
        run: terraform init

      - name: 'run jq'
        run: |
            terraform version -json | jq .
```
