### ISSUE TITLE
Use semantic versioning for jq releases

### ISSUE THREAD

**Issue by joelpurra** [stedolan/jq#558]
jq is being released too seldom. I think it's because there is no particular way you can tell if changes that are introduced are breaking compatibility, so everything has to wait until a _really_ breaking release comes along. All possible minor improvements, bug fixes and additions are hindered by development of these large or breaking changes.

Using semantic versioning would allow jq to release more often, while still letting users know that it wouldn't break their jq scripts.
https://semver.org/

**Comment by davidjeddy** [comment]
I would like to add my support to this imitative. X.Y.Z format release tagging. 

Ran into an issue recently where `1.6` is eval'd as a float, broke the application build pipeline. Of all the tools used to build the target application only jq has to have its version number encapsulated with quotes. :/

Excerpt:

```yml
versions:
  ...
  HELM_VER: 2.16.1
  JQ_VER: '1.6' # w/o quotes value is eval'd as a float
  TERRAFORM_VER: 0.12.18
  VAULT_VER: 1.1.0
  YQ_VER: 2.4.1
  ...
```

SemVer would bring jq inline with the very widely adopted tagging nomenclature of MAJOR.MINOR.PATCH.
